esphome:
  name: roundlcd

esp32:
  board: esp32-s3-devkitm-1
  framework:
    type: arduino

substitutions:
  tft_width: 320
  tft_height: 240

# psram:
#   mode: octal
#   speed: 80MHZ

#logger:

# wifi:
#   ssid: !secret wifi_ssid
#   password: !secret wifi_password

# captive_portal:

#api:

# ota:
#   - platform: esphome

# web_server:
#   port: 80

color:
  - id: my_red
    red: 100%
    green: 0%
    blue: 0%

# png must be RGB565
image:
  defaults:
    type: rgb565
    #transparency: opaque
    resize: 100x100
  images:
    - file: "weather.png"
      id: weather

spi:
  clk_pin: GPIO14
  mosi_pin: GPIO13
  
display: 
  - platform: mipi_spi
    model: ILI9341
    id: mylcd
    dc_pin: GPIO2
    #reset_pin: 0
    cs_pin: GPIO15
    dimensions:
      width: ${tft_width}
      height: ${tft_height}
    transform:
      swap_xy: true
      mirror_x: false
      mirror_y: false

lvgl:
  bg_color: black
  text_color: white
  buffer_size: 25%
  theme:
    label:
      text_color: white
  widgets:
  - obj:
      #align: CENTER
      width: ${tft_width}
      height: ${tft_height}
      bg_opa: TRANSP
      border_width: 0
      layout:
        type: GRID
        grid_columns: [FR(1), FR(1),FR(1)]
        grid_rows: [FR(10),FR(60),FR(20),FR(10)]
        #grid_column_align: STRETCH
      widgets:        
        - label:
            text: 'Melbourne'
            text_align: CENTER
            grid_cell_column_pos: 0
            grid_cell_row_pos: 0
        - image:
            src: weather
            grid_cell_column_pos: 0
            grid_cell_row_pos: 1
        - label:
            text: '21C'
            text_font: montserrat_40
            text_align: CENTER
            grid_cell_column_pos: 0 
            grid_cell_row_pos: 2
        - label:
            text: 'Updated 10:47'
            grid_cell_column_pos: 0
            grid_cell_row_pos: 3
