esphome:
  name: roundlcd

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# psram:
#   mode: octal
#   speed: 80MHZ

logger:

# wifi:
#   ssid: !secret wifi_ssid
#   password: !secret wifi_password

# captive_portal:

#api:

# ota:
#   - platform: esphome

# web_server:
#   port: 80

spi:
  clk_pin: GPIO12
  mosi_pin: GPIO11
  miso_pin: GPIO13

display: 
- platform: ili9xxx
  model: GC9A01A
  id: mylcd
  dc_pin: GPIO7
  reset_pin: GPIO4
  cs_pin: GPIO10
  rotation: 0
  invert_colors: false
  color_palette: 8BIT
  auto_clear_enabled: false
  lambda: |-
    it.filled_circle(20, 75, 10);

  
