esphome:
  name: roundlcd

esp32:
  board: esp32-s3-devkitm-1
  framework:
    type: arduino

# psram:
#   mode: octal
#   speed: 80MHZ

#logger:

# wifi:
#   ssid: !secret wifi_ssid
#   password: !secret wifi_password

# captive_portal:

#api:

# ota:
#   - platform: esphome

# web_server:
#   port: 80

color:
  - id: my_red
    red: 100%
    green: 0%
    blue: 0%

spi:
  clk_pin: GPIO14
  mosi_pin: GPIO13
  
display: 
  - platform: mipi_spi
    model: ILI9341
    id: mylcd
    dc_pin: GPIO2
    #reset_pin: 0
    cs_pin: GPIO15
    dimensions:
      width: 320
      height: 240
    transform:
      swap_xy: true
      mirror_x: false
      mirror_y: false

lvgl:
  bg_color: black
  text_color: white
  buffer_size: 25%
  widgets:
  - label:
      align: CENTER
      text: 'Hello World!'  
