esphome:
  name: roundlcd
  on_boot:
    then:
      - delay: 5s
      - logger.log: "Hello round LCD"

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# psram:
#   mode: octal
#   speed: 80MHZ

logger:
  level: VERBOSE

# wifi:
#   ssid: !secret wifi_ssid
#   password: !secret wifi_password

# captive_portal:

#api:

# ota:
#   - platform: esphome

# web_server:
#   port: 80

spi:
  clk_pin: GPIO2
  mosi_pin: GPIO4
  
display: 
  - platform: ili9xxx
    model: GC9A01A
    id: mylcd
    dc_pin: GPIO1
    reset_pin: GPIO0
    cs_pin: GPIO5
    rotation: 0
    invert_colors: false
    color_palette: 8BIT
    auto_clear_enabled: true
    lambda: |-
      it.filled_circle(20, 75, 10, Color(255,0,0,255));

  
